name: Test and Push

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: bitswan/pipeline-runtime-environment:2024-9191238548-git-9ad90fc
    
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Run tests
        run: |
          pytest

      - name: Run linter
        run: |
          black --check bs_shoveler bs_shoveler.py
          ruff check bs_shoveler bs_shoveler.py

    
  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Get Year and Commit Hash
      id: vars
      run: |
        echo "::set-output name=year::$(date +%Y)"
        echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Build and Push
      run: bash build_and_push.sh